#!/bin/bash

cp -v profile ~/.profile
echo "source ~/.profile" > ~/.zprofile
cp -v zlogin ~/.zlogin
cp -v zlogout ~/.zlogout
cp -v zshrc ~/.zshrc
cp -v zpreztorc ~/.zpreztorc
cp -vR zsh/ ~/.zsh

cp -v git.alias ~/.git.alias

cp -v gitconfig ~/.gitconfig

cp -v vimrc ~/.vimrc

cp -v screenrc ~/.screenrc

cp -v hushlogin ~/.hushlogin

cp -v sshconfig ~/.ssh/config

cp -v tmux.conf ~/.tmux.conf
