#!/bin/bash

set -e

echo $@
echo "lol"

# Can only handle 1 (or 0) args
if [ ${@[@]} -eq 1 ] || [ ${@[@]} -eq 0 ]; then
	DIR=${@[1]:-~} # default to ~
else
	echo "ERROR: copy can only handle 0 or 1 arguments."
	exit 1
fi

cp -v profile $DIR/.profile
ln -sf ~/.profile $DIR/.zprofile
cp -v zlogin $DIR/.zlogin
cp -v zlogout $DIR/.zlogout
cp -v zshrc $DIR/.zshrc
cp -v zimrc $DIR/.zimrc
cp wave.zsh-theme $DIR/.zim/modules/prompt/themes/wave.zsh-theme
ln -sf $DIR/.zim/modules/prompt/themes/wave.zsh-theme $DIR/.zim/modules/prompt/functions/prompt_wave_setup
cp -vR zsh/functions $DIR/.zsh

cp -v global_gitignore $DIR/.global_gitignore

cp -v git.alias $DIR/.git.alias

cp -v gitconfig $DIR/.gitconfig

cp -v vimrc $DIR/.vimrc

cp -v screenrc $DIR/.screenrc

cp -v inputrc $DIR/.inputrc

cp -v hushlogin $DIR/.hushlogin

cp -v sshconfig $DIR/.ssh/config

cp -v tmux.conf $DIR/.tmux.conf
