#!/bin/sh

if git diff --cached --diff-filter=ACMR | grep -c "@nocommit"; then
  # print the files that contain nocommit, including file name and the lines before and after the nocommit
  git diff -U --cached --diff-filter=ACMR | grep -B 1 -A 1 "@nocommit"
  echo "Commit aborted. Remove @nocommit from the files above to continue."
  exit 1
else
  # Run local pre-commit hook if exists
  if [ -e ./.git/hooks/pre-commit ]; then
    ./.git/hooks/pre-commit "$@"
  # if this is a worktree (i.e. `.git` is a file instead of a directory),
  elif [ -f ./.git ]; then
    # get the original git directory and assign to a local var
    git_dir=$(cat ./.git | sed 's/gitdir: //')
    # delete the last two directories from the path
    git_dir=${git_dir%/*/*}
    # run the pre-commit hook from the original git directory
    if [ -e "${git_dir}/hooks/pre-commit" ]; then
      "${git_dir}/hooks/pre-commit" "$@"
    else
      exit 0
    fi
  else
    exit 0
  fi
fi
