#!/bin/bash

set -e # exit if we encounter an error

DIRNAME=`dirname "$0"`
DIR=${1:-~} # default to ~ if a directory isn't specified

pushd $DIRNAME
./copy-shared
popd

# ubuntu specific \/

pushd $DIRNAME/.. # go up from scripts

cp -v profile.ubuntu $DIR/.profile.ubuntu

popd

set +e
